[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_cross_chain_exchange = "DzueqW4xsJRhv5pQdcwTsWgeKcV2xfEoKRALN4Ma8dHd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/mnt/c/Users/sonis/earn/confidential_cross_chain_exchange/artifacts/arcium_program_0.3.0.so"
