[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
confidential_cross_chain_exchange = "DzueqW4xsJRhv5pQdcwTsWgeKcV2xfEoKRALN4Ma8dHd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[test.validator]
[[test.genesis]]
address = "BKck65TgoKRokMjQM3datB9oRwJ8rAj2jxPXvHXUvcL6"
program = "/mnt/c/Users/sonis/earn/confidential-cross-chain-exchange/artifacts/arcium_program_0.3.0.so"

[[test.validator.account]]
address = "FHriyvoZotYiFnbUzKFjzRSb2NiaC8RPWY7jtKuKhg65"
filename = "artifacts/arcium_clock.json"

[[test.validator.account]]
address = "7MGSS4iKNM4sVib7bDZDJhVqB6EcchPwVnTKenCY1jt3"
filename = "artifacts/arcium_fee_pool.json"

[[test.validator.account]]
address = "BoVUVSJAhob2cvM5z4JZTdS6VWRSznh3bbzQD1TFjvDP"
filename = "artifacts/arx_mint.json"

[[test.validator.account]]
address = "G1qTVEvdcnd8LYqutH7PNcAyVm5vRohVxmCLJ6iJCQBx"
filename = "artifacts/wallet_acc_G1qT_CQBx.json"

[[test.validator.account]]
address = "9aLx2nboZtjFkJJEefXWQud3z2MAmaAcXpXN5X2Hvxnz"
filename = "artifacts/arx_ata_G1qT_CQBx.json"

[[test.validator.account]]
address = "FzgvEbRX5RKhgrVUqCnw2gLPFuRieycPspSJiLLzvYah"
filename = "artifacts/wallet_acc_Fzgv_vYah.json"

[[test.validator.account]]
address = "RJhFiwezDshHsSgiaGNBp1X21LncApFpxcbUTsNxY6n"
filename = "artifacts/wallet_acc_callback_RJhF_xY6n.json"

[[test.validator.account]]
address = "295ABETDgyxNLRi35mvoG6nhJpXZfvTSESbokCHukn2Q"
filename = "artifacts/arx_ata_Fzgv_vYah.json"

[[test.validator.account]]
address = "CbFUrx8QKUWRt8U7StbqKjRwceHbhFo4FXhTPyjNbvWq"
filename = "artifacts/operator_acc_Fzgv_vYah.json"

[[test.validator.account]]
address = "ELoRR19zrps1G3UYKcAxr7LKbw3kbqkVUXVY9dETMWN7"
filename = "artifacts/arx_node_Fzgv_vYah.json"

[[test.validator.account]]
address = "DLWzsbbyiTYGf3WXNMNB7RBA8idGazxMUFkx5HM9shoc"
filename = "artifacts/wallet_acc_DLWz_shoc.json"

[[test.validator.account]]
address = "AzXxb9DGW8JFY1oNhaNZs6AEM9NAopEnVPfrJUB4HTXd"
filename = "artifacts/wallet_acc_callback_AzXx_HTXd.json"

[[test.validator.account]]
address = "HbogdqWrWcHubYKK2KJG1yzSeXYSTBvsY83NxPw8XBQw"
filename = "artifacts/arx_ata_DLWz_shoc.json"

[[test.validator.account]]
address = "3MytDuA6bxe85xBG2kJJDPvQBBF9AYnkJ1EDM4UnvJjS"
filename = "artifacts/operator_acc_DLWz_shoc.json"

[[test.validator.account]]
address = "XdfSwb8ZajhN7CerfBSJVhyfx5fyLtv34QVKSRgMFA9"
filename = "artifacts/arx_node_DLWz_shoc.json"

[[test.validator.account]]
address = "GgSqqAyH7AVY3Umcv8NvncrjFaNJuQLmxzxFxPoPW2Yd"
filename = "artifacts/cluster_acc_0.json"

[[test.validator.account]]
address = "8a7JK5AFPt79fG5CGUFwx8UJ9dVJkQ6niZXtCYmALG62"
filename = "artifacts/add_together_raw_circuit_0.json"

[[test.validator.account]]
address = "8P7AU3VxuCXXhyyNT8NFAMVwdn6FVwGVxkZsZ1rPA3gM"
filename = "artifacts/confidential_deposit_native_raw_circuit_0.json"

[[test.validator.account]]
address = "HCvZzriNXWdHioTFr7CeCuVkxZfSRHnuFG3zzagA77hN"
filename = "artifacts/deposit_seller_native_raw_circuit_0.json"

[[test.validator.account]]
address = "5ehqhQtQoYVpmSj319v3y894WyryRN5pb112FggH6w71"
filename = "artifacts/deposit_seller_spl_raw_circuit_0.json"

[[test.validator.account]]
address = "E7Hfr2UagwybFDLatPFMXY74njLb6Q4VHteciLSMe1mr"
filename = "artifacts/finalize_interchain_origin_evm_offer_raw_circuit_0.json"

[[test.validator.account]]
address = "55JoMAUxSw9phbqSZe8CHNzCErUWrkHyZPa6fCV1UwGw"
filename = "artifacts/finalize_intrachain_offer_raw_circuit_0.json"

[[test.validator.account]]
address = "AwHhGPH5vdxBuJaM5nPjvPP7kLJH8awAU379cLQPeFZo"
filename = "artifacts/interchain_origin_evm_deposit_seller_spl_raw_circuit_0.json"

[[test.validator.account]]
address = "6YBos2w15tLEYDu87BbXyrupTAvUZDXmo9iBb8rSibtZ"
filename = "artifacts/relay_offer_clone_raw_circuit_0.json"

[[test.validator.account]]
address = "5MTHPi5YVVC2f81S4mXR5QT1WHDRwPSsqREi54VkbCTB"
filename = "artifacts/mxe_keygen_comp_def.json"

[[test.validator.account]]
address = "HnFn979pK57xELUHHcb5589fVbAUCZevu9GPbnoRHuUJ"
filename = "artifacts/mxe_keygen_comp.json"

[[test.validator.account]]
address = "9AhWqCiuu5Z4FMqc7SuUWUWc8iTSG6RnHFc5mZRWXJqj"
filename = "artifacts/mxe_acc.json"

[[test.validator.account]]
address = "Acwr2bPgH8QasP28aJbHZ49gk5XeHLi65nvjQGFzzM1u"
filename = "artifacts/mempool_acc.json"

[[test.validator.account]]
address = "HHKwZDcPqMuRErZeY3WWV5k3T6DVNpdMyt2yFn5y4DUG"
filename = "artifacts/executing_pool_acc.json"
